src/Entity/Candidate.php
<?php

namespace App\Entity;

use App\Repository\CandidateRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CandidateRepository::class)
 */
class Candidate
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255 , nullable=true)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255 , nullable=true)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=255 , nullable=true)
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=255 , nullable=true)
     */
    private $country;

    /**
     * @ORM\Column(type="string", length=255 , nullable=true)
     */
    private $nationality;

    /**
     * @ORM\Column(type="string", length=255 , nullable=true)
     */
    private $passport;

    /**
     * @ORM\Column(type="string", length=255 , nullable=true)
     */
    private $curriculum_vitae;

    /**
     * @ORM\Column(type="string", length=255 , nullable=true)
     */
    private $profil_picture;

    /**
     * @ORM\Column(type="string", length=255 , nullable=true)
     */
    private $current_location;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $date_of_birth;


     /**
      * @ORM\ManyToOne(targetEntity=Experience::class)
      */
     private $experience;

     /**
      * @ORM\OneToOne(targetEntity=InfosAdminCandidate::class, cascade={"persist", "remove"})
      * @ORM\JoinColumn(nullable=false)
      */
     private $info_admin_candidate;

     /**
      * @ORM\OneToOne(targetEntity=User::class, mappedBy="candidat", cascade={"persist", "remove"})
      */
     private $user;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getNationality(): ?string
    {
        return $this->nationality;
    }

    public function setNationality(string $nationality): self
    {
        $this->nationality = $nationality;

        return $this;
    }

    public function getPassport(): ?string
    {
        return $this->passport;
    }

    public function setPassport(string $passport): self
    {
        $this->passport = $passport;

        return $this;
    }

    public function getCurriculumVitae(): ?string
    {
        return $this->curriculum_vitae;
    }

    public function setCurriculumVitae(string $curriculum_vitae): self
    {
        $this->curriculum_vitae = $curriculum_vitae;

        return $this;
    }

    public function getProfilPicture(): ?string
    {
        return $this->profil_picture;
    }

    public function setProfilPicture(string $profil_picture): self
    {
        $this->profil_picture = $profil_picture;

        return $this;
    }

    public function getCurrentLocation(): ?string
    {
        return $this->current_location;
    }

    public function setCurrentLocation(string $current_location): self
    {
        $this->current_location = $current_location;

        return $this;
    }

    public function getDateOfBirth(): ?\DateTimeInterface
    {
        return $this->date_of_birth;
    }

    public function setDateOfBirth(\DateTimeInterface $date_of_birth): self
    {
        $this->date_of_birth = $date_of_birth;

        return $this;
    }


    public function getExperience(): ?Experience
    {
        return $this->experience;
    }

    public function setExperience(?Experience $experience): self
    {
        $this->experience = $experience;

        return $this;
    }

    public function getInfoAdminCandidate(): ?InfosAdminCandidate
    {
        return $this->info_admin_candidate;
    }

    public function setInfoAdminCandidate(InfosAdminCandidate $info_admin_candidate): self
    {
        $this->info_admin_candidate = $info_admin_candidate;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        // set the owning side of the relation if necessary
        if ($user->getCandidat() !== $this) {
            $user->setCandidat($this);
        }

        $this->user = $user;

        return $this;
    }


}

src/Form/CandidateType.php
<?php

namespace App\Form;

use App\Entity\Candidate;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
class CandidateType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('firstname')
            ->add('lastname')
            ->add('adress')
            ->add('country')
            ->add('nationality')
            ->add('passport')
            ->add('curriculum_vitae')
            ->add('profil_picture')
            ->add('current_location')
            ->add('date_of_birth', DateType::class,[
                'widget'=>'single_text',
                'format' => 'yyyy-MM-dd',
            ])
            ->add('experience')
            // ->add('info_admin_candidate')
            // ->add('user')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Candidate::class,
        ]);
    }
}

src/Controller/CandidateController.php
<?php

namespace App\Controller;

use App\Entity\Candidate;
use App\Form\CandidateType;
use App\Repository\CandidateRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/candidate")
 */
class CandidateController extends AbstractController
{
    /**
     * @Route("/", name="candidate_index", methods={"GET"})
     */
    public function index(CandidateRepository $candidateRepository): Response
    {
        return $this->render('candidate/index.html.twig', [
            'candidates' => $candidateRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="candidate_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $candidate = new Candidate();
        $form = $this->createForm(CandidateType::class, $candidate);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($candidate);
            $entityManager->flush();

            return $this->redirectToRoute('candidate_index');
        }

        return $this->render('candidate/new.html.twig', [
            'candidate' => $candidate,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="candidate_show", methods={"GET"})
     */
    public function show(Candidate $candidate): Response
    {
        return $this->render('candidate/show.html.twig', [
            'candidate' => $candidate,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="candidate_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Candidate $candidate): Response
    {
        $form = $this->createForm(CandidateType::class, $candidate);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('candidate_index');
        }

        return $this->render('candidate/edit.html.twig', [
            'candidate' => $candidate,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="candidate_delete", methods={"POST"})
     */
    public function delete(Request $request, Candidate $candidate): Response
    {
        if ($this->isCsrfTokenValid('delete'.$candidate->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($candidate);
            $entityManager->flush();
        }

        return $this->redirectToRoute('candidate_index');
    }
}

templates/candidate/_delete_form.html.twig
<form method="post" action="{{ path('candidate_delete', {'id': candidate.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ candidate.id) }}">
    <button class="btn">Delete</button>
</form>

templates/candidate/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/candidate/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Candidate{% endblock %}

{% block body %}
    <h1>Edit Candidate</h1>

    {{ include('candidate/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('candidate_index') }}">back to list</a>

    {{ include('candidate/_delete_form.html.twig') }}
{% endblock %}

templates/candidate/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Candidate index{% endblock %}

{% block body %}
    <h1>Candidate index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Firstname</th>
                <th>Lastname</th>
                <th>Adress</th>
                <th>Country</th>
                <th>Nationality</th>
                <th>Passport</th>
                <th>Curriculum_vitae</th>
                <th>Profil_picture</th>
                <th>Current_location</th>
                <th>Date_of_birth</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for candidate in candidates %}
            <tr>
                <td>{{ candidate.id }}</td>
                <td>{{ candidate.firstname }}</td>
                <td>{{ candidate.lastname }}</td>
                <td>{{ candidate.adress }}</td>
                <td>{{ candidate.country }}</td>
                <td>{{ candidate.nationality }}</td>
                <td>{{ candidate.passport }}</td>
                <td>{{ candidate.curriculumVitae }}</td>
                <td>{{ candidate.profilPicture }}</td>
                <td>{{ candidate.currentLocation }}</td>
                <td>{{ candidate.dateOfBirth ? candidate.dateOfBirth|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('candidate_show', {'id': candidate.id}) }}">show</a>
                    <a href="{{ path('candidate_edit', {'id': candidate.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="12">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('candidate_new') }}">Create new</a>
{% endblock %}

templates/candidate/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Candidate{% endblock %}

{% block body %}
    <h1>Create new Candidate</h1>

    {{ include('candidate/_form.html.twig') }}

    <a href="{{ path('candidate_index') }}">back to list</a>
{% endblock %}

templates/candidate/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Candidate{% endblock %}

{% block body %}
    <h1>Candidate</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ candidate.id }}</td>
            </tr>
            <tr>
                <th>Firstname</th>
                <td>{{ candidate.firstname }}</td>
            </tr>
            <tr>
                <th>Lastname</th>
                <td>{{ candidate.lastname }}</td>
            </tr>
            <tr>
                <th>Adress</th>
                <td>{{ candidate.adress }}</td>
            </tr>
            <tr>
                <th>Country</th>
                <td>{{ candidate.country }}</td>
            </tr>
            <tr>
                <th>Nationality</th>
                <td>{{ candidate.nationality }}</td>
            </tr>
            <tr>
                <th>Passport</th>
                <td>{{ candidate.passport }}</td>
            </tr>
            <tr>
                <th>Curriculum_vitae</th>
                <td>{{ candidate.curriculumVitae }}</td>
            </tr>
            <tr>
                <th>Profil_picture</th>
                <td>{{ candidate.profilPicture }}</td>
            </tr>
            <tr>
                <th>Current_location</th>
                <td>{{ candidate.currentLocation }}</td>
            </tr>
            <tr>
                <th>Date_of_birth</th>
                <td>{{ candidate.dateOfBirth ? candidate.dateOfBirth|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('candidate_index') }}">back to list</a>

    <a href="{{ path('candidate_edit', {'id': candidate.id}) }}">edit</a>

    {{ include('candidate/_delete_form.html.twig') }}
{% endblock %}